### ISSUE TITLE
blog example lack of detailed documentation

### ISSUE THREAD

**Issue by ifyour** [yusukebe/honox-examples#2]
In the `blog` example, when I run `npm run dev`, I get the following error on the console:

``
D1_ERROR: no such table: articles
``

May I ask if there are any steps that I have erred in this example?  It looks like I'm not synchronizing the table structure to local SQLite.

**Comment by ifyour** [comment]
Based on the feedback from this [issue](https://github.com/honojs/vite-plugins/issues/24#issuecomment-1903769841), it's working fine for me, but I'm a little confused as to whether this is unintended behavior of the plugin.

```bash
mkdir -p .mf/d1/DB
sqlite3 .mf/d1/DB/db.sqlite < blog.sql
```

Then run `npm run dev` and it works fine.

**Comment by ongnxco** [comment]
> Based on the feedback from this [issue](https://github.com/honojs/vite-plugins/issues/24#issuecomment-1903769841), it's working fine for me, but I'm a little confused as to whether this is unintended behavior of the plugin.
> 
> ```shell
> mkdir -p .mf/d1/DB
> sqlite3 .mf/d1/DB/db.sqlite < blog.sql
> ```
> 
> Then run `npm run dev` and it works fine. Or is there a better way to initialize the table structure to local SQLite? 🤣

Its still not working

```
POST  /articles/create
GET   /articles/create
POST  /articles/preview
GET   /articles/:id
GET   /
GET   /*
D1_ERROR: no such table: articles
```

**Comment by ifyour** [comment]
@ongnxco Are you executing the path correctly? I tested that it is working.

```bash
npm i sqlite3 -g
```

```bash
cd projects/blog
mkdir -p .mf/d1/DB
sqlite3 .mf/d1/DB/db.sqlite < blog.sql
```

**Comment by ongnxco** [comment]
It would be nice if it was automatic like this https://hub.nuxt.com/docs/recipes/drizzle#migrations
